# OWID Metrics Configuration
# 
# Add any metric from Our World in Data here.
# The app will automatically import data on startup/deploy.
#
# Format:
#   metric_name:
#     owid_slug: the-slug-from-owid-url
#     start_year: 1990
#     end_year: 2024
#     unit: "%" or "score (0-10)" etc.
#     description: "Human readable description"
#     category: economy | social | development | health | environment | innovation
#     aggregation_method: population_weighted  # or sum, average
#     enabled: true  # set to false to disable without removing
#
# To find slugs: Visit https://ourworldindata.org/charts
# Example URL: https://ourworldindata.org/grapher/renewable-energy-consumption
# Slug is: renewable-energy-consumption
#
# Categories:
#   - economy: GDP, income, employment, trade
#   - social: Population, demographics, quality of life
#   - development: Infrastructure, education, basic services
#   - health: Healthcare, disease, mortality
#   - environment: Climate, emissions, energy, resources
#   - innovation: R&D, technology, patents

health_expenditure_gdp_percent:
  owid_slug: total-healthcare-expenditure-gdp
  start_year: 2000
  end_year: 2024
  unit: "% of GDP"
  description: "Health expenditure as a percentage of GDP"
  category: health
  aggregation_method: population_weighted
  enabled: true

life_satisfaction:
  owid_slug: happiness-cantril-ladder
  start_year: 2005
  end_year: 2024
  unit: "score (0-10)"
  description: "Life satisfaction score on the Cantril Ladder"
  category: social
  aggregation_method: population_weighted
  enabled: true

child_mortality_rate:
  owid_slug: child-mortality
  start_year: 1990
  end_year: 2024
  unit: "%"
  description: "Child mortality rate (deaths per 100 live births)"
  category: development
  aggregation_method: population_weighted
  enabled: true

electricity_access:
  owid_slug: share-of-the-population-with-access-to-electricity
  start_year: 1990
  end_year: 2024
  unit: "%"
  description: "Access to electricity (% of population)"
  category: development
  aggregation_method: population_weighted
  enabled: true

gdp_per_capita_ppp:
  owid_slug: gdp-per-capita-worldbank
  start_year: 1990
  end_year: 2024
  unit: "international $"
  description: "GDP per capita (PPP, constant 2017 international $)"
  category: economy
  aggregation_method: population_weighted
  enabled: true

healthy_life_expectancy:
  owid_slug: healthy-life-expectancy-at-birth
  start_year: 1990
  end_year: 2024
  unit: "years"
  description: "Healthy life expectancy at birth"
  category: health
  aggregation_method: population_weighted
  enabled: true

fertility_rate:
  owid_slug: children-born-per-woman
  start_year: 1990
  end_year: 2024
  unit: "births per woman"
  description: "Fertility rate (children born per woman)"
  category: social
  aggregation_method: population_weighted
  enabled: true

labor_productivity_per_hour:
  owid_slug: labor-productivity-per-hour-pennworldtable
  start_year: 1990
  end_year: 2024
  unit: "output per hour (2017 $)"
  description: "Labor productivity per hour worked"
  category: economy
  aggregation_method: population_weighted
  enabled: true

median_income_daily:
  owid_slug: daily-median-income
  start_year: 1990
  end_year: 2024
  unit: "$ per day"
  description: "Daily median income (PPP-adjusted)"
  category: economy
  aggregation_method: population_weighted
  enabled: true

poorest_10_percent_income:
  owid_slug: daily-income-or-consumption-of-the-poorest-10-marimekko
  start_year: 1990
  end_year: 2024
  unit: "$ per day"
  description: "Daily income or consumption of the poorest 10%"
  category: social
  aggregation_method: population_weighted
  enabled: true
